name: CI - PR validation

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.10.0

      - run: npm i -g yarn --force
      - run: yarn
      - run: yarn test
      - run: yarn husky-build
      - run: yarn lint
