name: CI - PR validation

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Installing package manager
        run: npm i -g yarn

      - name: Installing dependencies
        run: yarn

      - name: Run test
        run: yarn test

      - name: Shadow build test
        run: yarn husky-build

      - name: Check code linting
        run: yarn lint
